#!/bin/bash
# Copyright (c) 2018, 2019, Oracle and/or its affiliates. All rights reserved.

zonefile=$1
ip=$2
name=$3

if [ $(grep ^$name $zonefile | grep -qs $ip ; echo $?) != 0 ]
then
    echo "$name  IN      A       $ip" >> $zonefile
fi

systemctl reload named
